version: "2"

services: 
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    build: ./kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.86.100
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "chatmsg:1:1"    
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  server:
    build: ./server
    command: nodemon --debug -L server.js #default port debug port 5858
    volumes:
      - ./server:/app
    ports:
      - "4000:4000"
      - "5858:5858"
    depends_on:
      - "zookeeper"
      - "kafka"
 
  ui:
    build: ./ui
    command: nodemon --debug -L server.js #default port debug port 5858    
    volumes:
      - ./ui:/ui
    ports:
      - "3000:3000"
      - "5959:5858"