version: "2"

services: 
  server:
    build: ./server
    command: nodemon --debug -L server.js
    volumes:
      - ./server:/app
    ports:
      - "8080:8080"
      - "5858:5858"
    networks:
      - front-tier
      - back-tier

  ui:
    build: ./ui
    #command: nodemon --debug -L server.js
    command: node server.js
    volumes:
      - ./ui:/ui
    ports:
      - "3000:3000"
     # - "5959:5858"
    networks:
      - front-tier
      - back-tier      

networks:
    front-tier:
    back-tier: